# Generated by Django 4.2.4 on 2023-08-25 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fb_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupadmin',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='groupadmin',
            name='group',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='group',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='member',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='GroupAdmin',
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
    ]
