# Generated by Django 3.0 on 2023-08-25 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment6', '0002_comment_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(choices=[('WOW', 'Wow'), ('LIT', 'Lit'), ('LOVE', 'Love'), ('HAHA', 'Haha'), ('THUMBS-UP', 'Thumbs Up'), ('THUMBS-DOWN', 'Thumbs Down'), ('ANGRY', 'Angry'), ('SAD', 'Sad')], max_length=100)),
                ('reacted_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assignment6.Comment')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assignment6.Post')),
                ('reacted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment6.User')),
            ],
        ),
    ]
